return {
  -- {
  --   -- NOTE: this remove lsp mappings
  --   "nvim-mini/mini.operators",
  --   event = "VeryLazy",
  --   opts = {
  --     evaluate = { prefix = "" },
  --     multiply = { prefix = "gm" },
  --     -- use <C-c> to cancel exchange
  --     exchange = { prefix = "X" },
  --     replace = { prefix = "" },
  --     sort = { prefix = "go" },
  --   },
  -- },
  -- {
  --   -- NOTE: no necessary?
  --   "nvim-mini/mini.move",
  --   event = "VeryLazy",
  --   opts = {
  --     mappings = {
  --       -- Move visual selection in Visual mode.
  --       left = "<M-Left>",
  --       right = "<M-Right>",
  --       down = "<M-Down>",
  --       up = "<M-Up>",
  --
  --       -- Move current line in Normal mode
  --       line_left = "<M-Left>",
  --       line_right = "<M-Right>",
  --       line_down = "<M-Down>",
  --       line_up = "<M-Up>",
  --     },
  --     options = {
  --       reindent_linewise = false,
  --     },
  --   },
  -- },
  -- {
  --   -- NOTE: no necessary? caso contrario documentarlo en el futuro
  --   "kevinhwang91/nvim-fundo",
  --   dependencies = { "kevinhwang91/promise-async" },
  --   event = "VeryLazy",
  --   config = function()
  --     require("fundo").setup()
  --     vim.api.nvim_exec_autocmds("BufReadPost", { group = "Fundo", modeline = false })
  --   end,
  -- },
  -- {
  --   -- NOTE: a util o fix
  --   "nmac427/guess-indent.nvim",
  --   event = "VeryLazy",
  --   opts = {
  --     on_tab_options = {
  --       ["expandtab"] = false,
  --       ["tabstop"] = vim.o.tabstop,
  --       ["shiftwidth"] = 0,
  --     },
  --     on_space_options = {
  --       ["expandtab"] = true,
  --       ["tabstop"] = vim.o.tabstop,
  --       ["softtabstop"] = "detected",
  --       ["shiftwidth"] = "detected",
  --     },
  --   },
  --   config = function(_, opts)
  --     require("guess-indent").setup(opts)
  --     require("guess-indent").set_from_buffer(nil, true, true)
  --   end,
  -- },
  -- {
  --   -- NOTE: a util o fix, solo es necesario en windows?
  --   "tpope/vim-eunuch",
  --   -- stylua: ignore
  --   cmd = {
  --     "Unlink",
  --     "Remove",
  --     "Delete",
  --     "Move", "Rename", "Copy", "Duplicate",
  --     "Chmod",
  --     "Mkdir",
  --     "Cfind", "Clocate",
  --     "Lfind", "Llocate",
  --     "SudoWrite",
  --     "SudoEdit",
  --     "Wall", "W",
  --   },
  -- },
}
