return {
  { import = "plugins.extras.coding.blink" },
  { import = "plugins.extras.coding.colorful_menu" },
  { import = "plugins.extras.coding.neogen" },
  { import = "plugins.extras.coding.supermaven" },
  { import = "plugins.extras.coding.cmp_extras" },
  { import = "plugins.extras.coding.cmp_snippet" },

  { import = "plugins.extras.editor.conform" },
  { import = "plugins.extras.editor.fzf" },
  { import = "plugins.extras.editor.fzf_profile" },
  { import = "plugins.extras.editor.refactoring" },
  { import = "plugins.extras.editor.todo_comments" },
  { import = "plugins.extras.editor.nvim_highlight_colors" },

  { import = "plugins.extras.ui.cokeline" },
  { import = "plugins.extras.ui.colorscheme" },
  { import = "plugins.extras.ui.heirline" },
  { import = "plugins.extras.ui.nvim_bqf" },
  { import = "plugins.extras.ui.treesitter_context" },

  { import = "plugins.extras.util.bloat" },
  { import = "plugins.extras.util.cloak" },
  { import = "plugins.extras.util.emoji" },
  { import = "plugins.extras.util.git_messenger" },
  { import = "plugins.extras.util.harpoon" },
  { import = "plugins.extras.util.markdown_preview" },
  { import = "plugins.extras.util.multicursor" },
  { import = "plugins.extras.util.neotab" },
  { import = "plugins.extras.util.obsidian" },
  { import = "plugins.extras.util.kulala" },
  { import = "plugins.extras.util.showkeys" },
  { import = "plugins.extras.util.startuptime" },
  { import = "plugins.extras.util.mini_clue" },

  { import = "plugins.extras.lang.astro" },
  { import = "plugins.extras.lang.blade" },
  -- { import = "plugins.extras.lang.cmake" },
  { import = "plugins.extras.lang.ejs" },
  { import = "plugins.extras.lang.go" },
  { import = "plugins.extras.lang.java" },
  { import = "plugins.extras.lang.json" },
  -- { import = "plugins.extras.lang.latex" },
  { import = "plugins.extras.lang.lua" },
  { import = "plugins.extras.lang.php" },
  { import = "plugins.extras.lang.python" },
  { import = "plugins.extras.lang.sql" },
  { import = "plugins.extras.lang.tailwind" },
  { import = "plugins.extras.lang.typescript" },
  { import = "plugins.extras.lang.typst" },
  { import = "plugins.extras.lang.vue" },

  { import = "plugins.extras.lang.csharp" },
  { import = "plugins.extras.lang.css" },

  {
    "blink.cmp",
    optional = true,
    version = false,
    build = "cargo build --release",
  },

  {
    "toggleterm.nvim",
    optional = true,
    opts = {
      shell = "cmd /s /k clink inject",
    },
  },
}
